name: Actions

on: [pull_request]

jobs:
  API_Testing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v
      - uses: actions/setup-node
        with:
          node-version: "14.x"
      - run: npm run api-testing
